const F={id:'ID Projeto',name:'Projeto',client:'Cliente',segment:'Segmento',director:'Diretor',status:'Status',risk:'Risco',delay:'Desvio Prazo (dias)',fees:'Honorarios Contratados',revenue:'Receita Reconhecida',billed:'Valor Faturado',received:'Valor Recebido',backlog:'Backlog',forecastCost:'Custo Projetado Final',margin:'Margem Prevista',progress:'Progresso Real',satisfaction:'Satisfacao Cliente'};
const projects=window.PROJECTS||[];
const colors={'Em andamento':'#1d6989','Planejado':'#79bfd1','Em espera':'#f08b43','Concluido':'#39856f','Cancelado':'#9d526e'};
const $=s=>document.querySelector(s);
const els={segment:$('#segmentFilter'),status:$('#statusFilter'),risk:$('#riskFilter'),director:$('#directorFilter'),search:$('#searchFilter')};
const money=n=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',notation:'compact',maximumFractionDigits:1}).format(n||0);
const pct=n=>`${((n||0)*100).toFixed(1).replace('.',',')}%`;
const num=n=>new Intl.NumberFormat('pt-BR').format(Math.round(n||0));
const sum=(arr,key)=>arr.reduce((a,p)=>a+(Number(p[key])||0),0);
const avg=(arr,key)=>{const v=arr.map(p=>Number(p[key])).filter(Number.isFinite);return v.length?v.reduce((a,b)=>a+b,0)/v.length:0};
const uniq=key=>[...new Set(projects.map(p=>p[key]).filter(Boolean))].sort((a,b)=>String(a).localeCompare(String(b),'pt-BR'));
function fillSelect(el,key){uniq(key).forEach(v=>el.add(new Option(v,v)))}
fillSelect(els.segment,F.segment);fillSelect(els.status,F.status);fillSelect(els.risk,F.risk);fillSelect(els.director,F.director);

function filtered(){const q=els.search.value.trim().toLocaleLowerCase('pt-BR');return projects.filter(p=>(!els.segment.value||p[F.segment]===els.segment.value)&&(!els.status.value||p[F.status]===els.status.value)&&(!els.risk.value||p[F.risk]===els.risk.value)&&(!els.director.value||p[F.director]===els.director.value)&&(!q||`${p[F.name]} ${p[F.client]} ${p[F.id]}`.toLocaleLowerCase('pt-BR').includes(q)))}
function stats(data){const fees=sum(data,F.fees),revenue=sum(data,F.revenue),cost=sum(data,F.forecastCost),billed=sum(data,F.billed),received=sum(data,F.received);return{count:data.length,active:data.filter(p=>['Em andamento','Em espera'].includes(p[F.status])).length,fees,revenue,backlog:sum(data,F.backlog),margin:fees?(fees-cost)/fees:0,receivable:billed-received,high:data.filter(p=>p[F.risk]==='Alto').length,delayed:data.filter(p=>Number(p[F.delay])>30&&!['Concluido','Cancelado'].includes(p[F.status])).length,satisfaction:avg(data,F.satisfaction)}}
function group(data,key){return data.reduce((a,p)=>{const k=p[key]||'Não informado';(a[k]??=[]).push(p);return a},{})}

function renderKpis(data){const s=stats(data);const items=[['Projetos ativos',num(s.active),`${s.high} em risco alto`,s.high>0],['Honorários',money(s.fees),`${num(data.length)} projetos na seleção`],['Receita reconhecida',money(s.revenue),`${pct(s.fees?s.revenue/s.fees:0)} do contratado`],['Backlog',money(s.backlog),'receita futura contratada'],['Margem prevista',pct(s.margin),'sobre honorários atuais',s.margin<.3],['A receber',money(s.receivable),`satisfação média ${s.satisfaction.toFixed(1).replace('.',',')}`]];$('#kpis').innerHTML=items.map(x=>`<div class="kpi ${x[3]?'warning':''}"><span>${x[0]}</span><strong>${x[1]}</strong><small>${x[2]}</small></div>`).join('');const total=stats(projects);$('#executiveSummary').textContent=`A carteira reúne ${total.count} projetos e ${money(total.fees)} em honorários. O valor está contratado; a agenda executiva agora é converter ${money(total.backlog)} de backlog em receita, sem ceder margem nos projetos mais pressionados.`}
function renderDonut(data){const groups=group(data,F.status);const order=['Em andamento','Planejado','Em espera','Concluido','Cancelado'];let cursor=0;const stops=[];order.forEach(k=>{const n=(groups[k]||[]).length;const end=cursor+(data.length?n/data.length*100:0);if(n)stops.push(`${colors[k]} ${cursor}% ${end}%`);cursor=end});$('#statusDonut').style.background=stops.length?`conic-gradient(${stops.join(',')})`:'#e4ebee';$('#donutTotal').textContent=data.length;$('#statusLegend').innerHTML=order.filter(k=>(groups[k]||[]).length).map(k=>{const n=groups[k].length;return`<div class="legend-row"><i style="background:${colors[k]}"></i><span>${k}</span><strong>${n} · ${Math.round(n/data.length*100)}%</strong></div>`}).join('')||'<p>Sem projetos nesta seleção.</p>'}
function renderSegments(data){const groups=group(data,F.segment);const values=Object.entries(groups).map(([k,v])=>({k,fees:sum(v,F.fees),backlog:sum(v,F.backlog)})).sort((a,b)=>b.fees-a.fees);const max=Math.max(...values.map(v=>v.fees),1);$('#segmentChart').innerHTML=values.map(v=>`<div class="bar-row"><span title="${v.k}">${v.k}</span><div class="bar-track"><i class="bar-fees" style="width:${v.fees/max*100}%"></i><i class="bar-backlog" style="width:${v.backlog/max*100}%"></i></div><span class="bar-value">${money(v.fees)}</span></div>`).join('')||'<p>Sem dados.</p>'}
function renderScatter(data){const box={w:680,h:285,l:52,r:18,t:18,b:35};const ds=data.filter(p=>Number.isFinite(Number(p[F.margin]))&&Number.isFinite(Number(p[F.delay])));const xMin=-25,xMax=130,yMin=.1,yMax=.5;const X=x=>box.l+(Math.max(xMin,Math.min(xMax,x))-xMin)/(xMax-xMin)*(box.w-box.l-box.r);const Y=y=>box.t+(yMax-Math.max(yMin,Math.min(yMax,y)))/(yMax-yMin)*(box.h-box.t-box.b);let svg=`<svg viewBox="0 0 ${box.w} ${box.h}" preserveAspectRatio="none">`;[-20,0,30,60,90,120].forEach(x=>{svg+=`<line class="${x===0?'zero-line':'gridline'}" x1="${X(x)}" x2="${X(x)}" y1="${box.t}" y2="${box.h-box.b}"/><text class="axis-label" x="${X(x)}" y="${box.h-12}" text-anchor="middle">${x}d</text>`});[.1,.2,.3,.4,.5].forEach(y=>{svg+=`<line class="gridline" x1="${box.l}" x2="${box.w-box.r}" y1="${Y(y)}" y2="${Y(y)}"/><text class="axis-label" x="${box.l-8}" y="${Y(y)+3}" text-anchor="end">${Math.round(y*100)}%</text>`});ds.forEach((p,i)=>{const radius=3.5+Math.sqrt((Number(p[F.fees])||0)/400000);svg+=`<circle tabindex="0" class="dot ${p[F.risk]==='Alto'?'high':''}" cx="${X(Number(p[F.delay]))}" cy="${Y(Number(p[F.margin]))}" r="${Math.min(11,radius)}" data-i="${i}"/>`});svg+='</svg>';$('#scatterChart').innerHTML=svg;const tip=$('#tooltip');$('#scatterChart').querySelectorAll('.dot').forEach(dot=>{const p=ds[Number(dot.dataset.i)];const show=e=>{tip.innerHTML=`<strong>${p[F.name]}</strong><br>${p[F.risk]} risco · ${Number(p[F.delay])} dias<br>Margem ${pct(p[F.margin])} · ${money(p[F.fees])}`;tip.style.left=`${Math.min(innerWidth-250,e.clientX+14)}px`;tip.style.top=`${e.clientY+14}px`;tip.classList.add('show')};dot.addEventListener('mousemove',show);dot.addEventListener('mouseleave',()=>tip.classList.remove('show'));dot.addEventListener('focus',e=>show({clientX:innerWidth/2,clientY:innerHeight/2}));dot.addEventListener('blur',()=>tip.classList.remove('show'))})}
function renderThesis(data){const s=stats(data);const segs=Object.entries(group(data,F.segment)).map(([k,v])=>[k,sum(v,F.fees)]).sort((a,b)=>b[1]-a[1]);const lead=segs[0]||['—',0],concentration=s.fees?lead[1]/s.fees:0;const active=data.filter(p=>['Em andamento','Em espera'].includes(p[F.status]));const highFees=sum(data.filter(p=>p[F.risk]==='Alto'),F.fees);const items=[['Escala contratada',`${money(s.fees)} em honorários e ${money(s.backlog)} ainda por converter sustentam visibilidade de receita.`],['Diversificação',`${lead[0]} é o maior segmento, com ${pct(concentration)} da carteira selecionada — concentração relevante, mas não dominante.`],['Disciplina de execução',`${s.delayed} projetos ativos superam 30 dias de desvio. O foco deve ser recuperação de prazo sem consumir a margem de ${pct(s.margin)}.`],['Capital relacional',`Satisfação média de ${s.satisfaction.toFixed(1).replace('.',',')} e ${active.length} projetos ativos criam uma plataforma para recorrência e novas unidades.`]];$('#thesisList').innerHTML=items.map((x,i)=>`<div class="thesis-item"><b>${String(i+1).padStart(2,'0')}</b><div><strong>${x[0]}</strong><p>${x[1]}</p></div></div>`).join('')}
function renderTable(data){const sorted=[...data].sort((a,b)=>{const score=p=>(p[F.risk]==='Alto'?10000000:0)+Math.max(0,Number(p[F.delay]))*50000+(Number(p[F.fees])||0);return score(b)-score(a)}).slice(0,12);$('#projectTable').innerHTML=sorted.map(p=>`<tr><td><strong>${p[F.name]}</strong></td><td>${p[F.client]}</td><td>${p[F.segment]}</td><td><span class="status-badge">${p[F.status]}</span></td><td><span class="risk-badge risk-${p[F.risk]}">${p[F.risk]}</span></td><td class="num ${Number(p[F.delay])>30?'negative':''}">${Number(p[F.delay])>0?'+':''}${num(p[F.delay])}d</td><td class="num">${money(p[F.fees])}</td><td class="num">${money(p[F.backlog])}</td><td class="num ${Number(p[F.margin])<.25?'negative':''}">${pct(p[F.margin])}</td></tr>`).join('')||'<tr><td colspan="9">Nenhum projeto encontrado.</td></tr>';$('#portfolioCount').textContent=`TOP ${Math.min(12,sorted.length)} DE ${data.length} PROJETOS`}
function update(){const data=filtered();renderKpis(data);renderDonut(data);renderSegments(data);renderScatter(data);renderThesis(data);renderTable(data)}
Object.values(els).forEach(el=>el.addEventListener(el===els.search?'input':'change',update));$('#clearFilters').addEventListener('click',()=>{Object.values(els).forEach(el=>el.value='');update()});

const all=stats(projects);const segments=Object.entries(group(projects,F.segment)).map(([k,v])=>({k,v:sum(v,F.fees)})).sort((a,b)=>b.v-a.v);const topSegment=segments[0];const highProjects=projects.filter(p=>p[F.risk]==='Alto');const story=[
 {k:'01 · A ABERTURA',title:`O escritório já construiu <em>escala contratada.</em>`,text:`A carteira soma ${money(all.fees)} em honorários distribuídos por ${all.count} projetos. Não estamos apresentando uma promessa abstrata: existe uma base contratada e diversificada.`,number:money(all.fees),unit:'HONORÁRIOS CONTRATADOS',caption:`${all.active} projetos ativos no corte de agosto de 2026.`},
 {k:'02 · A VISIBILIDADE',title:`O próximo crescimento já está <em>dentro da carteira.</em>`,text:`O backlog de ${money(all.backlog)} representa receita futura contratada. O desafio estratégico não é apenas vender mais — é transformar esse estoque em receita com previsibilidade.`,number:money(all.backlog),unit:'BACKLOG CONTRATADO',caption:`Equivale a ${pct(all.fees?all.backlog/all.fees:0)} dos honorários totais.`},
 {k:'03 · A QUALIDADE',title:`Crescer vale mais quando a <em>margem permanece.</em>`,text:`A margem prevista consolidada é de ${pct(all.margin)}. Ela mostra uma operação economicamente atraente, mas também define a linha que a execução não pode atravessar.`,number:pct(all.margin),unit:'MARGEM PREVISTA',caption:`Receita reconhecida: ${money(all.revenue)}.`},
 {k:'04 · A TENSÃO',title:`O valor está contratado. O risco está na <em>execução.</em>`,text:`Há ${all.high} projetos classificados como risco alto e ${all.delayed} projetos ativos com atraso superior a 30 dias. Esses contratos concentram a agenda de proteção de valor.`,number:num(all.high),unit:'PROJETOS EM RISCO ALTO',caption:`Atraso, avanço físico e custo projetado orientam a classificação.`},
 {k:'05 · A TESE',title:`A oportunidade é converter escala em <em>repetibilidade.</em>`,text:`${topSegment.k} lidera a carteira, mas o portfólio atravessa oito segmentos. A tese para o investidor combina três movimentos: acelerar o backlog, recuperar projetos críticos e transformar satisfação em recorrência.`,number:topSegment.k.toUpperCase(),unit:'MAIOR SEGMENTO',caption:`${money(topSegment.v)} em honorários, com diversificação ao redor.`}
];
let storyIndex=0;function storyBars(){return segments.slice(0,5).map(s=>`<div class="story-bar"><span>${s.k}</span><i style="width:${s.v/segments[0].v*100}%"></i><b>${money(s.v)}</b></div>`).join('')}
function renderStory(){const s=story[storyIndex];$('#storySlide').innerHTML=`<div><span class="story-kicker">${s.k}</span><h2>${s.title}</h2><p>${s.text}</p></div><div class="story-visual"><div class="story-number">${s.number}</div><div class="story-unit">${s.unit}</div><div class="story-caption">${s.caption}</div>${storyIndex===4?`<div class="story-bars">${storyBars()}</div>`:''}</div>`;$('#storyCounter').textContent=`${String(storyIndex+1).padStart(2,'0')} / ${String(story.length).padStart(2,'0')}`;$('#storyProgress').style.setProperty('--progress',`${(storyIndex+1)/story.length*100}%`);$('#prevStory').disabled=storyIndex===0;$('#nextStory').textContent=storyIndex===story.length-1?'Concluir':'Próximo →'}
function openStory(){storyIndex=0;renderStory();$('#storyOverlay').classList.add('open');$('#storyOverlay').setAttribute('aria-hidden','false');document.body.style.overflow='hidden';$('#closeStory').focus()}
function closeStory(){$('#storyOverlay').classList.remove('open');$('#storyOverlay').setAttribute('aria-hidden','true');document.body.style.overflow='';$('#openStory').focus()}
$('#openStory').addEventListener('click',openStory);$('#closeStory').addEventListener('click',closeStory);$('#prevStory').addEventListener('click',()=>{if(storyIndex>0){storyIndex--;renderStory()}});$('#nextStory').addEventListener('click',()=>{if(storyIndex<story.length-1){storyIndex++;renderStory()}else closeStory()});document.addEventListener('keydown',e=>{if(!$('#storyOverlay').classList.contains('open'))return;if(e.key==='Escape')closeStory();if(e.key==='ArrowRight'&&storyIndex<story.length-1){storyIndex++;renderStory()}if(e.key==='ArrowLeft'&&storyIndex>0){storyIndex--;renderStory()}});
update();
